name:    mysql-yesod-demo
version: "0.0.0"

dependencies:
- base
- bytestring
- monad-logger
- persistent
- persistent-mysql
- persistent-template
- resourcet
- text
- yesod-core
- yesod-persistent

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  mysql-yesod-demo:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mysql-yesod-demo
